version: '3'

services:
  registry:
    image: registry:latest
    container_name: docker_registry
    ports:
      - "5000:5000"
    restart: always
    version: "3.8"

  my-service:
    image: mcr.microsoft.com/windows/nanoserver:1809
registries:
  mcr:
    url: https://mcr.microsoft.com
    auth:
      username: "<awm>"
      password: "<awm@12345>"
